[project]
name = "ayon-openassetio-manager-plugin"
version = "0.2.0"
requires-python = ">=3.10,<3.14"
authors = [
    { name="AYON Team", email = "info@ynput.io" }
]
description = "AYON Manager Plugin for OpenAssetIO hosts."
keywords = ["AYON", "OpenAssetIO", "asset", "automation", "tracking", "asset management"]
readme = "README.md"
license = {file = "LICENSE"}

# Using unlocked version until everything stabilizes
dependencies = [
    "ayon-python-api",
    # ~/.local/share/AYON/addons/core_1.3.2 - dependencies not available
    # in dependency_packages:
    "platformdirs",
    "semver",
    "arrow",
    "attrs",
    # Support caching
    "cachetools",
    "openassetio-traitgen"
]

[project.optional-dependencies]
# For UI delegates. Assumes PySide/PyQt is already available in the Python
# environment.
ui = [
    "qtpy",
    "qtawesome==0.7.3"
]
# For cases where OpenAssetIO is not already available in the Python
# environment, which should be rare, e.g. unit tests.
openassetio = [
    "openassetio>=1.0.0",
    "openassetio-mediacreation>=1.0.0a12",
]

[project.urls]
homepage = "https://github.com/ynput/ayon-openassetio-manager-plugin"
repository = "https://github.com/ynput/ayon-openassetio-manager-plugin"

[project.entry-points."openassetio.manager_plugin"]
plugin_package_or_module = "ayon_openassetio_manager"

[project.entry-points."openassetio.ui_plugin"]
plugin_package_or_module = "ayon_openassetio_manager.ui"

[tool.black]
line-length = 99

[tool.ruff]
line-length = 99

[tool.setuptools.packages.find]
where = ["plugin"]

[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"
